# Streaming Platform Content Strategy Using TVMaze API

## Project Overview
This project focuses on collecting TV show data from TVMaze API and converting the raw JSON responses into structured CSV files. The collected data will later be used to analyze content types, genres, languages, ratings, runtime, networks, and release trends.

## Business Context
As the founder of a streaming platform, I need data-driven insights to decide which types of content to promote, license, or invest in. Understanding genres, ratings, languages, and content availability can support better content strategy and user engagement.

## Problem Statement
The streaming platform needs to make better content acquisition and promotion decisions. Without data, it may invest in content types or genres that do not match audience preferences or quality indicators. By analyzing TV show genres, ratings, languages, networks, and release trends, the platform can identify which content areas are more valuable to prioritize.

## Research Questions
As the founder of a streaming platform, these questions will help guide content strategy and investment decisions:

1. Which genres have the highest average ratings and should be prioritized for content acquisition?
2. Which languages are most common in the available TV show catalog?
3. Does runtime have any relationship with average show rating?
4. Which networks produce the highest-rated shows?
5. How has TV show production changed over time based on premiere dates?
6. Which content types or genres should the platform prioritize based on both rating and availability?

## Data Source & Collection Method
The data was collected using API requests from the TVMaze public API. Since the Shows API is paginated, multiple pages were requested using the page parameter. The final dataset contains 750 TV show records. The API returned the data in JSON format, then it was converted into structured CSV files using Python and Pandas.

API endpoint used:
- Shows API: https://api.tvmaze.com/shows

## Date of Data Collection
May 3, 2026

## Goal of This Step
The goal of this step is to collect show data from the API, convert it from JSON format into structured CSV files, and preview the data before starting the full analysis.

In [6]:
import requests
import pandas as pd
import time

print("Libraries imported successfully.")

Libraries imported successfully.

In [7]:

all_shows = []

# Collect shows from multiple pages to get at least 500 records
for page in range(3):
    url = f"https://api.tvmaze.com/shows?page={page}"
    response = requests.get(url)

    print(f"Page {page} status code:", response.status_code)

    if response.status_code == 200:
        page_data = response.json()
        all_shows.extend(page_data)
    else:
        print(f"Stopped at page {page}")
        break

    time.sleep(0.5)

shows_df = pd.DataFrame(all_shows)

print("Total collected shows:", len(shows_df))
shows_df.head()

Page 0 status code: 200
Page 1 status code: 200
Page 2 status code: 200
Total collected shows: 727

,id,url,name,type,language,genres,status,runtime,averageRuntime,premiered,...,rating,weight,network,webChannel,dvdCountry,externals,image,summary,updated,_links
0,1,https://www.tvmaze.com/shows/1/under-the-dome,Under the Dome,Scripted,English,"[Drama, Science-Fiction, Thriller]",Ended,60.0,60.0,2013-06-24,...,{'average': 6.6},100,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",None,None,"{'tvrage': 25988, 'thetvdb': 264492, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p><b>Under the Dome</b> is the story of a sma...,1769177765,{'self': {'href': 'https://api.tvmaze.com/show...
1,2,https://www.tvmaze.com/shows/2/person-of-interest,Person of Interest,Scripted,English,"[Action, Crime, Science-Fiction]",Ended,60.0,60.0,2011-09-22,...,{'average': 8.8},99,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",None,None,"{'tvrage': 28376, 'thetvdb': 248742, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>You are being watched. The government has a...,1773594169,{'self': {'href': 'https://api.tvmaze.com/show...
2,3,https://www.tvmaze.com/shows/3/bitten,Bitten,Scripted,English,"[Drama, Horror, Romance]",Ended,60.0,60.0,2014-01-11,...,{'average': 7.4},98,"{'id': 7, 'name': 'CTV Sci-Fi Channel', 'count...",None,None,"{'tvrage': 34965, 'thetvdb': 269550, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Based on the critically acclaimed series of...,1704793709,{'self': {'href': 'https://api.tvmaze.com/show...
3,4,https://www.tvmaze.com/shows/4/arrow,Arrow,Scripted,English,"[Drama, Action, Science-Fiction]",Ended,60.0,60.0,2012-10-10,...,{'average': 7.4},99,"{'id': 5, 'name': 'The CW', 'country': {'name'...",None,None,"{'tvrage': 30715, 'thetvdb': 257655, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>After a violent shipwreck, billionaire play...",1766868900,{'self': {'href': 'https://api.tvmaze.com/show...
4,5,https://www.tvmaze.com/shows/5/true-detective,True Detective,Scripted,English,"[Drama, Crime, Thriller]",Running,60.0,63.0,2014-01-12,...,{'average': 8.1},100,"{'id': 8, 'name': 'HBO', 'country': {'name': '...",None,None,"{'tvrage': 31369, 'thetvdb': 270633, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Touch darkness and darkness touches you bac...,1777231753,{'self': {'href': 'https://api.tvmaze.com/show...

In [ ]:
shows_data = shows_response.json()

shows_df = pd.DataFrame(shows_data)

shows_df.head()

,id,url,name,type,language,genres,status,runtime,averageRuntime,premiered,...,rating,weight,network,webChannel,dvdCountry,externals,image,summary,updated,_links
0,1,https://www.tvmaze.com/shows/1/under-the-dome,Under the Dome,Scripted,English,"[Drama, Science-Fiction, Thriller]",Ended,60.0,60,2013-06-24,...,{'average': 6.6},100,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",None,None,"{'tvrage': 25988, 'thetvdb': 264492, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p><b>Under the Dome</b> is the story of a sma...,1769177765,{'self': {'href': 'https://api.tvmaze.com/show...
1,2,https://www.tvmaze.com/shows/2/person-of-interest,Person of Interest,Scripted,English,"[Action, Crime, Science-Fiction]",Ended,60.0,60,2011-09-22,...,{'average': 8.8},99,"{'id': 2, 'name': 'CBS', 'country': {'name': '...",None,None,"{'tvrage': 28376, 'thetvdb': 248742, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>You are being watched. The government has a...,1773594169,{'self': {'href': 'https://api.tvmaze.com/show...
2,3,https://www.tvmaze.com/shows/3/bitten,Bitten,Scripted,English,"[Drama, Horror, Romance]",Ended,60.0,60,2014-01-11,...,{'average': 7.4},97,"{'id': 7, 'name': 'CTV Sci-Fi Channel', 'count...",None,None,"{'tvrage': 34965, 'thetvdb': 269550, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Based on the critically acclaimed series of...,1704793709,{'self': {'href': 'https://api.tvmaze.com/show...
3,4,https://www.tvmaze.com/shows/4/arrow,Arrow,Scripted,English,"[Drama, Action, Science-Fiction]",Ended,60.0,60,2012-10-10,...,{'average': 7.4},98,"{'id': 5, 'name': 'The CW', 'country': {'name'...",None,None,"{'tvrage': 30715, 'thetvdb': 257655, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,"<p>After a violent shipwreck, billionaire play...",1766868900,{'self': {'href': 'https://api.tvmaze.com/show...
4,5,https://www.tvmaze.com/shows/5/true-detective,True Detective,Scripted,English,"[Drama, Crime, Thriller]",Running,60.0,63,2014-01-12,...,{'average': 8.1},100,"{'id': 8, 'name': 'HBO', 'country': {'name': '...",None,None,"{'tvrage': 31369, 'thetvdb': 270633, 'imdb': '...",{'medium': 'https://static.tvmaze.com/uploads/...,<p>Touch darkness and darkness touches you bac...,1777231753,{'self': {'href': 'https://api.tvmaze.com/show...

In [8]:
shows_structured = pd.DataFrame({
    "show_id": shows_df["id"],
    "name": shows_df["name"],
    "type": shows_df["type"],
    "language": shows_df["language"],
    "genres": shows_df["genres"].apply(lambda x: ", ".join(x) if isinstance(x, list) else None),
    "status": shows_df["status"],
    "runtime": shows_df["runtime"],
    "average_runtime": shows_df["averageRuntime"],
    "premiered": shows_df["premiered"],
    "ended": shows_df["ended"],
    "official_site": shows_df["officialSite"],
    "rating_average": shows_df["rating"].apply(lambda x: x.get("average") if isinstance(x, dict) else None),
    "network_name": shows_df["network"].apply(lambda x: x.get("name") if isinstance(x, dict) else None),
    "country_name": shows_df["network"].apply(lambda x: x.get("country", {}).get("name") if isinstance(x, dict) and x.get("country") else None),
    "country_code": shows_df["network"].apply(lambda x: x.get("country", {}).get("code") if isinstance(x, dict) and x.get("country") else None),
    "summary": shows_df["summary"]
})

print("Structured dataset shape:", shows_structured.shape)
shows_structured.head()

Structured dataset shape: (727, 16)

,show_id,name,type,language,genres,status,runtime,average_runtime,premiered,ended,official_site,rating_average,network_name,country_name,country_code,summary
0,1,Under the Dome,Scripted,English,"Drama, Science-Fiction, Thriller",Ended,60.0,60.0,2013-06-24,2015-09-10,http://www.cbs.com/shows/under-the-dome/,6.6,CBS,United States,US,<p><b>Under the Dome</b> is the story of a sma...
1,2,Person of Interest,Scripted,English,"Action, Crime, Science-Fiction",Ended,60.0,60.0,2011-09-22,2016-06-21,http://www.cbs.com/shows/person_of_interest/,8.8,CBS,United States,US,<p>You are being watched. The government has a...
2,3,Bitten,Scripted,English,"Drama, Horror, Romance",Ended,60.0,60.0,2014-01-11,2016-04-15,http://bitten.space.ca/,7.4,CTV Sci-Fi Channel,Canada,CA,<p>Based on the critically acclaimed series of...
3,4,Arrow,Scripted,English,"Drama, Action, Science-Fiction",Ended,60.0,60.0,2012-10-10,2020-01-28,None,7.4,The CW,United States,US,"<p>After a violent shipwreck, billionaire play..."
4,5,True Detective,Scripted,English,"Drama, Crime, Thriller",Running,60.0,63.0,2014-01-12,None,https://www.max.com/shows/true-detective/9a4a3...,8.1,HBO,United States,US,<p>Touch darkness and darkness touches you bac...

In [9]:
shows_df.to_csv("shows_raw.csv", index=False)
shows_structured.to_csv("shows_structured.csv", index=False)

print("CSV files saved successfully.")
print("Raw dataset shape:", shows_df.shape)
print("Structured dataset shape:", shows_structured.shape)

CSV files saved successfully.
Raw dataset shape: (727, 23)
Structured dataset shape: (727, 16)